[package]
name = "dipak_site"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
axum = { version = "0.7.7" , features = ["multipart"]}
tokio = { version = "1.41.1", features = ["full"] }
futures = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

tower-http = { version = "0.6.2", features = ["fs"] }
tower = "0.5.1"
tower-sessions = "0.13.0"
axum_csrf = "0.10.2"

chrono = { version = "0.4.38", features = ["serde"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }


diesel = { version = "2.2.5", default-features = false, features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
time = "0.3.36"
regex = "1.11.1"

ammonia = "4.0.0"
indexmap = { version = "2.6.0", features = ["serde"] }
argon2 = "0.6.0-pre.1"
uuid = { version = "1.11.0", features = ["v4"] }
cookie = "0.18.1"
# [build-dependencies]
# diesel_cli = { version = "2.0", default-features = false, features = ["sqlite"] }


[profile.dev.package.askama_derive]
opt-level = 3
