services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - RUST_LOG=info
        volumes:
            - ./templates:/usr/src/app/templates
            - ./static:/usr/src/app/static
            - ./media:/usr/src/app/media
            - ./dipakdb.sqlite3:/usr/src/app/dipakdb.sqlite3
            - ./profile.json:/usr/src/app/profile.json
            - ./.env:/usr/src/app/.env
        depends_on:
            - database

    database:
        image: postgres:latest
        container_name: database
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./.env:/usr/src/app/.env
            - ./.postgres_data:/var/lib/postgresql/data
