FROM rust:latest AS builder

WORKDIR /usr/src/app

COPY media .
COPY migrations .
COPY src .
COPY static .
COPY templates .
COPY .env .
COPY Cargo.* .
COPY diesel.* .

RUN cargo install cargo-watch

CMD ["cargo", "build"]

CMD ["cargo", "watch", "-x", "run"]
