services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-prod
    restart: always
    ports:
      - "80:80" # HTTP traffic
      - "443:443" # HTTPS traffic
      - "81:81" # Admin UI (Access this to set up SSL)
    volumes:
      - ./nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - webnet
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dipak_site-webapp-prod
    restart: always
    # Ports removed from host; Nginx will find it on 'webnet' via container port 8081
    expose:
      - "8081"
    env_file:
      - .env
    volumes:
      - app_logs:/tmp/logs/dipakniroula.com.np/
    networks:
      - webnet
      - internal
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db-prod
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal

volumes:
  postgres_data:
  app_logs:


networks:
  webnet:
  internal:
