global:
  scrape_interval: 5s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: "rust_app"
    static_configs:
      - targets: [ "webapp:8080" ]

  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:9464" ]